---
title: Equivalence_Partition
---
classDiagram
    class ValuePartition{
        +String name
        +String Type
    }
    ValuePartition <|-- StringPartition
    class StringPartition{
        +int minimumLength
        +string minErrorMsg
        +int maxLength
        +string maxErrorMsg
        +enum allowed_chars
        +string notAllowedCharErrorMsg
        +List~char~ forbidden_chars
        +string forbidden_charsErrorMsg
    }

    ValuePartition <|-- NumberPartition
    class NumberPartition{
        +float min
        +string minErrorMsg
        +float max
        +string maxErrorMsg
    }

    ValuePartition <|-- EnumPartition
    class EnumPartition{
        +List~String~ values
        +string UnknownValueErrorMsg
    }

    ValuePartition <|-- BooleanPartition
    class BooleanPartition{
    }

