---
title: TestCase
---
classDiagram
    class TestCase{

        +String name
        +String module_name
        +String function_name
        +ArrayList~name, datatype~ args
        +~name, datatype~ test_arg
        +String condition
        +String Expected_Value

        +TestCase createCopy()
        +String generateTestCode()
    }
    class TestCaseCollection{
        +String name
        +List~TestCase~ testcases

        +AddTestCase(Testcase)
        +RemoveTestCase(Testcase)
    }

    class variable{
        String value
        Type type
    }

    class Type{

    }

    TestCaseCollection o-- TestCase
    variable *-- TestCase
    Type *-- variable